"""No-oracle global initialization, refinement, failure and file contracts."""
import importlib.util
import json
from pathlib import Path
import subprocess
import sys
from unittest.mock import patch

import numpy as np
import pytest
import spatialrust as sr

EXAMPLES=Path(__file__).resolve().parents[1]/'examples'


@pytest.fixture
def module(monkeypatch):
    monkeypatch.syspath_prepend(str(EXAMPLES))
    spec=importlib.util.spec_from_file_location('global_example',EXAMPLES/'align_global.py')
    module=importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def fixture():
    target=np.random.default_rng(12).uniform(-1,1,(600,3)).astype(np.float32)
    angle=np.deg2rad(60)
    rotation=np.array([[np.cos(angle),-np.sin(angle),0],[np.sin(angle),np.cos(angle),0],[0,0,1]])
    source=(target@rotation.T+[3,-2,.5]).astype(np.float32)
    schedule=[dict(leaf=.1,max_distance=.5,iterations=30),dict(leaf=None,max_distance=.1,iterations=30)]
    return source,target,schedule


def test_global_generation_recovers_large_pose_without_input_prior(module):
    source,target,schedule=fixture()
    aligned,report=module.align_global_clouds(sr.PointCloud.from_xyz(source),sr.PointCloud.from_xyz(target),schedule)
    np.testing.assert_allclose(aligned.xyz(),target,atol=5e-5)
    assert not report['initial_transform_supplied']
    selection=report['candidate_selection']
    assert [r['seed'] for r in selection['candidates']] == [7,8,9]
    assert selection['successful_candidates'] == 3
    keys=[(r['aligned_support']['distance_gated_points'],-r['aligned_support']['gated_rmse_metres']) for r in selection['candidates']]
    assert selection['selected_index'] == max(range(3),key=lambda i:keys[i])
    from render_alignment_report import render_report
    rendered=render_report(report)
    assert 'generated by FPFH/RANSAC; no caller-supplied pose' in rendered
    assert 'default identity' not in rendered
    assert 'Seeds in candidate order: 7, 8, 9' in rendered
    report['initial_transform_supplied']=True
    with pytest.raises(ValueError,match='caller supplied'):
        render_report(report)


@pytest.mark.parametrize('settings',[
    {'seeds':[]},{'seeds':[7,7]},{'seeds':[True]},{'seeds':[-1]},{'seeds':[2**64]},
    {'global_leaf':0},{'feature_radius':float('inf')},{'global_distance':-1},
    {'ransac_iterations':0},{'normal_neighbors':2},{'max_coarse_points':2},
    {'minimum_support':float('nan')},{'evaluation_distance':0},
])
def test_invalid_options_before_io(module,settings):
    _,_,schedule=fixture()
    with patch.object(sr,'read',side_effect=AssertionError('read before validation')):
        with pytest.raises(ValueError):
            module.align_global_files('missing','missing',schedule,**settings)


def test_global_point_budget_before_descriptor_work(module):
    source,target,schedule=fixture()
    with patch.object(sr,'register_fpfh_ransac',side_effect=AssertionError('descriptor work')):
        with pytest.raises(ValueError,match='max_coarse_points'):
            module.align_global_clouds(sr.PointCloud.from_xyz(source),sr.PointCloud.from_xyz(target),schedule,max_coarse_points=3)


def test_failed_global_seed_is_reported_and_remaining_seed_can_succeed(module):
    source,target,schedule=fixture()
    original=sr.register_fpfh_ransac
    def attempt(*args,**kwargs):
        if kwargs['seed']==7:
            raise ValueError('controlled failed hypothesis')
        return original(*args,**kwargs)
    with patch.object(sr,'register_fpfh_ransac',side_effect=attempt):
        _,report=module.align_global_clouds(sr.PointCloud.from_xyz(source),sr.PointCloud.from_xyz(target),schedule,seeds=[7,8])
    records=report['candidate_selection']['candidates']
    assert records[0]['status']=='error'
    assert records[0]['error']=='controlled failed hypothesis'
    assert report['candidate_selection']['selected_index']==1
    from render_alignment_report import render_report
    assert 'controlled failed hypothesis' in render_report(report)


def test_no_accepted_global_hypothesis_is_not_refined(module):
    class Failed:
        converged=False
        fitness=float('inf')
    source,target,schedule=fixture()
    with patch.object(sr,'register_fpfh_ransac',return_value=Failed()),patch.object(module,'align_multiscale_clouds',side_effect=AssertionError('refinement')):
        with pytest.raises(ValueError,match='no global hypothesis succeeded'):
            module.align_global_clouds(sr.PointCloud.from_xyz(source),sr.PointCloud.from_xyz(target),schedule)


def test_cli_full_source_roundtrip_and_exclusive_output(module,tmp_path):
    source,target,schedule=fixture()
    paths=[tmp_path/'source.pcd',tmp_path/'target.pcd']
    sr.write(str(paths[0]),sr.PointCloud.from_xyz(source));sr.write(str(paths[1]),sr.PointCloud.from_xyz(target))
    config=tmp_path/'schedule.json';config.write_text(json.dumps(schedule))
    output=tmp_path/'aligned'
    command=[sys.executable,str(EXAMPLES/'align_global.py'),*map(str,paths),'--schedule',str(config),'--output-dir',str(output),'--html-report']
    result=subprocess.run(command,capture_output=True,text=True,timeout=60)
    assert result.returncode==0,result.stderr
    np.testing.assert_allclose(sr.read(str(output/'aligned.pcd')).xyz(),target,atol=5e-5)
    saved=(output/'aligned.pcd').read_bytes()
    assert subprocess.run(command,capture_output=True,timeout=60).returncode!=0
    assert (output/'aligned.pcd').read_bytes()==saved


def test_global_output_preserves_typed_attributes_and_rotates_normals(module,tmp_path):
    import pyarrow as pa
    from test_alignment_attributes import write_rich_pcd
    source,target,schedule=fixture()
    normals=np.tile([0,1,0],(len(source),1)).astype(np.float32)
    path=tmp_path/'rich.pcd'
    intensity,labels,timestamps=write_rich_pcd(path,source,normals)
    original=sr.read(str(path))
    aligned,report=module.align_global_clouds(original,sr.PointCloud.from_xyz(target),schedule)
    columns=pa.array(aligned)
    assert aligned.field_names()==original.field_names()
    for name,expected in [('intensity',intensity),('label',labels),('timestamp',timestamps)]:
        np.testing.assert_array_equal(columns.field(name).to_numpy(),expected)
    actual=np.column_stack([columns.field('normal_'+axis).to_numpy() for axis in 'xyz'])
    np.testing.assert_allclose(actual,normals@np.asarray(report['transform_source_to_target'])[:3,:3].T,atol=2e-6)
    np.testing.assert_array_equal(original.xyz(),source)


def test_unknown_file_options_rejected_before_io(module):
    _,_,schedule=fixture()
    with patch.object(sr,'read',side_effect=AssertionError('IO')):
        with pytest.raises(TypeError):
            module.align_global_files('missing','missing',schedule,unknown=True)


@pytest.mark.parametrize('field,value',[
    ('seeds',[8,7,9]),('max_coarse_points',3),('normal_neighbors',2),
    ('normal_orientation','unknown'),('fitness_definition','nearest_point_rmse'),
])
def test_renderer_rejects_inconsistent_global_metadata(module,field,value):
    source,target,schedule=fixture()
    _,report=module.align_global_clouds(sr.PointCloud.from_xyz(source),sr.PointCloud.from_xyz(target),schedule)
    report['global_initialization'][field]=value
    from render_alignment_report import render_report
    with pytest.raises(ValueError):
        render_report(report)


def test_optional_geometry_diagnostics_share_full_source_counts(module):
    source,target,schedule=fixture()
    _,report=module.align_global_clouds(sr.PointCloud.from_xyz(source),sr.PointCloud.from_xyz(target),schedule,include_geometry=True)
    assert report['geometry_diagnostics']['source']['points']==len(source)
    assert report['geometry_diagnostics']['target']['rank']==6
    from render_alignment_report import render_report
    assert 'local information rank 6/6' in render_report(report)
    report['geometry_diagnostics']['source']['points']-=1
    with pytest.raises(ValueError,match='point count'):render_report(report)
